name: "terraform-destroy"
on: workflow_dispatch
jobs:
  terraform:
    name: "Terraform-Destroy"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: |
          rm -rf .terraform
          terraform init
        working-directory: "./cloudwatch-module"

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: "./cloudwatch-module"

